### PR TITLE
add openrouter ai

### PR DESCRIPTION
**Pull request by christoic**

### CODE REVIEW

**Comment by christoic** [comment]
Add configuration for openrouter ai

**Comment by Myzel394** [comment]
What happened here? Seems like you deleted your repo, which resulted in the PR being closed

**Comment by christoic** [comment]
My bad.
Do you want me to reopen a PR.
My proposal was to add openai as an additional provider (more flexible one).

**Comment by Myzel394** [comment]
Yeah if you'd like to, you can reopen it

**Pull request closed without merging**
